---
version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements_dev.txt
      - pylint index.py
      - flake8 index.py
      - pydocstyle -v index.py
      - yamllint .
  build:
    commands:
      - pip install -r requirements.txt -t .
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
